### ISSUE TITLE
should [proof assistant] be translated to [证明助理] or to [辅助定理证明器]

### ISSUE THREAD

**Issue by lolisa** [lolisa/SFCT#10]
The first one is a direct translation, while the second one preserve the correspondence of Automated Theorem Prover, which is translated into [自动化定理证明器]

**Comment by ruoz** [comment]
为了对应的话还是第二个好些吧……

**Comment by bctnry** [comment]
感觉第二个读起来有点拗口又冗长……【证明助理】就是个挺好的翻译

**Comment by dramforever** [comment]
I would go for 证明助理. We need not compress unnecessary information into the name as long as it does not cause confusion.

**Comment by lolisa** [comment]
I also agree that 证明助理 is better. In addition, the one that should preserve the correspondence is more like interactive theorem prover.

**Comment by izgzhen** [comment]
@lolisa What about a glossary table plus a translator? We can write [proof assistant] amid Chinese which will be translated by program to a defined correspondence, like 证明助理. Even better, we can generate Glossary table, attach original English to its Chinese translation in a unified way, or make link to wikipedia....

Drop by 挖坑而已，要是太烦可以忽视我....

**Comment by lolisa** [comment]
We already have a glossary table... Thx for the suggestion, will definitely consider the rest you say...
