### ISSUE TITLE
Unify term used in translation

### ISSUE THREAD

**Issue by lolisa** [lolisa/SFCT#3]

**Comment by dramforever** [comment]
This problem will never be settled, as there are always new terms found in the process. Do we start an issue for every problem word found? Or perhaps let's just turn this thread as the discussion thread for term translations.

For example, although "分类讨论" seems standard and fine, "分类" for "case" seems really awkward, and I suggest "情况"。"销毁" for "destruct" sounds a bit dangerous, and is confusing in "auto doesn't destruct hypotheses", just I don't really have anything to suggest for this.

We could have a list in the top comment. We have checkboxes in GFM, just write something like

    - [ ] Unchecked
    - [X] Checked

to get:

- [ ] Unchecked
- [X] Checked

But you have to change the markdown source to change the status.

Yes I know I can change your comments. No I don't want to do it, as it's up to the whole group.

**Comment by lolisa** [comment]
What's GFM?
I dont know, but this seems to me that I'll make this issues list too long. Maybe we should have a unique label for such problem.

**Comment by bctnry** [comment]
for the word "destruct" I suggest "解构"
